"""Add provider column to user_api_keys

Revision ID: 0201baa3bdc5
Revises: de627de58b84
Create Date: 2026-02-08 15:22:30.260911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0201baa3bdc5'
down_revision = 'de627de58b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    user_api_keys_columns = {column['name'] for column in inspector.get_columns('user_api_keys')}
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        if 'provider' not in user_api_keys_columns:
            batch_op.add_column(sa.Column('provider', sa.String(length=20), nullable=True))

    user_profiles_columns = {column['name'] for column in inspector.get_columns('user_profiles')}
    user_profiles_foreign_keys = inspector.get_foreign_keys('user_profiles')
    has_vertex_fk = any(
        fk.get('referred_table') == 'vertex_service_accounts'
        and fk.get('constrained_columns') == ['selected_vertex_account_id']
        for fk in user_profiles_foreign_keys
    )

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        if 'ai_provider' not in user_profiles_columns:
            batch_op.add_column(sa.Column('ai_provider', sa.String(length=20), nullable=True))
        if 'selected_vertex_account_id' not in user_profiles_columns:
            batch_op.add_column(sa.Column('selected_vertex_account_id', sa.Integer(), nullable=True))
        if 'vertex_location' not in user_profiles_columns:
            batch_op.add_column(sa.Column('vertex_location', sa.String(length=50), nullable=True))
        if not has_vertex_fk:
            batch_op.create_foreign_key(
                'fk_user_profiles_selected_vertex_account_id_vertex_service_accounts',
                'vertex_service_accounts',
                ['selected_vertex_account_id'],
                ['id']
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    user_profiles_columns = {column['name'] for column in inspector.get_columns('user_profiles')}
    user_profiles_foreign_keys = inspector.get_foreign_keys('user_profiles')

    fk_name = None
    for foreign_key in user_profiles_foreign_keys:
        if foreign_key.get('referred_table') == 'vertex_service_accounts' and foreign_key.get('constrained_columns') == ['selected_vertex_account_id']:
            fk_name = foreign_key.get('name')
            break

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        if fk_name:
            batch_op.drop_constraint(fk_name, type_='foreignkey')
        if 'vertex_location' in user_profiles_columns:
            batch_op.drop_column('vertex_location')
        if 'selected_vertex_account_id' in user_profiles_columns:
            batch_op.drop_column('selected_vertex_account_id')
        if 'ai_provider' in user_profiles_columns:
            batch_op.drop_column('ai_provider')

    user_api_keys_columns = {column['name'] for column in inspector.get_columns('user_api_keys')}
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        if 'provider' in user_api_keys_columns:
            batch_op.drop_column('provider')

    # ### end Alembic commands ###
