"""add_rag_documents_chunks_and_citations

Revision ID: 05f47b96438f
Revises: 72af56f10c29
Create Date: 2026-02-15 09:23:05.912393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f47b96438f'
down_revision = '72af56f10c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_analysis_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('citation_meta', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_analysis_reports', schema=None) as batch_op:
        batch_op.drop_column('citation_meta')
        batch_op.drop_column('citations')

    # ### end Alembic commands ###
