"""add_role_and_rag_tables

Revision ID: 3a2056c22526
Revises: 7c571eebe133
Create Date: 2026-02-16 11:47:50.088933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision = '3a2056c22526'
down_revision = '7c571eebe133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('heading', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
        batch_op.drop_index(batch_op.f('ix_rag_chunks_qdrant_point_id'))
        batch_op.drop_index(batch_op.f('ix_rag_chunks_rag_document_id'))
        batch_op.create_index(batch_op.f('ix_rag_chunks_document_id'), ['document_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('rag_chunks_rag_document_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rag_documents', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('rag_document_id')
        batch_op.drop_column('section')
        batch_op.drop_column('page')
        batch_op.drop_column('qdrant_point_id')

    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('gcs_path', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('file_size', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_rag_documents_file_upload_id'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_user_id'))
        batch_op.create_index(batch_op.f('ix_rag_documents_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_unique_constraint(None, ['gcs_path'])
        batch_op.drop_constraint(batch_op.f('rag_documents_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('rag_documents_file_upload_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('file_upload_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('indexed_at')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('error_message')
        batch_op.drop_column('ocr_used')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='user', nullable=False))

    with op.batch_alter_table('video_analysis_reports', schema=None) as batch_op:
        batch_op.drop_column('citations')
        batch_op.drop_column('citation_meta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_analysis_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('citation_meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('citations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('indexed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('file_upload_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rag_documents_file_upload_id_fkey'), 'file_uploads', ['file_upload_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('rag_documents_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_rag_documents_uploaded_by'))
        batch_op.create_index(batch_op.f('ix_rag_documents_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_file_upload_id'), ['file_upload_id'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('metadata')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('file_size')
        batch_op.drop_column('gcs_path')
        batch_op.drop_column('content_type')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qdrant_point_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('section', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rag_document_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rag_chunks_rag_document_id_fkey'), 'rag_documents', ['rag_document_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_rag_chunks_document_id'))
        batch_op.create_index(batch_op.f('ix_rag_chunks_rag_document_id'), ['rag_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_chunks_qdrant_point_id'), ['qdrant_point_id'], unique=False)
        batch_op.drop_column('embedding')
        batch_op.drop_column('page_number')
        batch_op.drop_column('heading')
        batch_op.drop_column('content')
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###
