"""add behavioral cognitive analysis columns to video analysis reports

Revision ID: 3b581523c33c
Revises: b54d56cbd82c
Create Date: 2026-03-03 14:17:54.000381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b581523c33c'
down_revision = 'b54d56cbd82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_analysis_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_emotional_analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cognitive_analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('adaptive_behavior_analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('selfcare_analysis', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_analysis_reports', schema=None) as batch_op:
        batch_op.drop_column('selfcare_analysis')
        batch_op.drop_column('adaptive_behavior_analysis')
        batch_op.drop_column('cognitive_analysis')
        batch_op.drop_column('social_emotional_analysis')

    # ### end Alembic commands ###
