"""add video_analysis_reports table

Revision ID: 72af56f10c29
Revises: 0201baa3bdc5
Create Date: 2026-02-10 17:34:08.086119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72af56f10c29'
down_revision = '0201baa3bdc5'
branch_labels = None
depends_on = None


def upgrade():
    # This migration has historically run against environments where index
    # names differ or are already missing, so only drop the table when present.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'child_video_analysis_reports' in inspector.get_table_names():
        op.drop_table('child_video_analysis_reports')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_video_analysis_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('child_age_months', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('result_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pdf_storage_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('pdf_gcs_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('child_video_analysis_reports_child_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('child_video_analysis_reports_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video_records.id'], name=op.f('child_video_analysis_reports_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('child_video_analysis_reports_pkey'))
    )
    with op.batch_alter_table('child_video_analysis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_video_analysis_reports_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_video_analysis_reports_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_video_analysis_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_video_analysis_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_video_analysis_reports_child_id'), ['child_id'], unique=False)

    # ### end Alembic commands ###
