"""change embedding dimension from 768 to 1536

Revision ID: b54d56cbd82c
Revises: b8f34c8377bf
Create Date: 2026-02-28 16:02:49.372985

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision = 'b54d56cbd82c'
down_revision = 'b8f34c8377bf'
branch_labels = None
depends_on = None


def upgrade():
    # Clear existing 768-dim embeddings before resizing the column
    op.execute('UPDATE rag_chunks SET embedding = NULL WHERE embedding IS NOT NULL')

    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)

    # ### end Alembic commands ###
