"""add enriched_content to rag_chunks

Revision ID: b8f34c8377bf
Revises: 3a2056c22526
Create Date: 2026-02-28 15:32:25.109084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f34c8377bf'
down_revision = '3a2056c22526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enriched_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.drop_column('enriched_content')

    # ### end Alembic commands ###
