"""empty message

Revision ID: de627de58b84
Revises: 831f5b74bbc6
Create Date: 2026-02-05 11:40:03.950348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de627de58b84'
down_revision = '831f5b74bbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    if 'translations' in table_names:
        translation_indexes = {idx['name'] for idx in inspector.get_indexes('translations')}
        with op.batch_alter_table('translations', schema=None) as batch_op:
            if 'ix_translations_key' in translation_indexes:
                batch_op.drop_index('ix_translations_key')
            if 'ix_translations_locale' in translation_indexes:
                batch_op.drop_index('ix_translations_locale')
        op.drop_table('translations')

    if 'missing_translations' in table_names:
        missing_translation_indexes = {idx['name'] for idx in inspector.get_indexes('missing_translations')}
        with op.batch_alter_table('missing_translations', schema=None) as batch_op:
            if 'ix_missing_translations_key' in missing_translation_indexes:
                batch_op.drop_index('ix_missing_translations_key')
            if 'ix_missing_translations_locale' in missing_translation_indexes:
                batch_op.drop_index('ix_missing_translations_locale')
        op.drop_table('missing_translations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missing_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requested_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_requested', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('auto_translated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('missing_translations_pkey')),
    sa.UniqueConstraint('locale', 'key', name=op.f('uix_missing_locale_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('missing_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missing_translations_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_missing_translations_key'), ['key'], unique=False)

    op.create_table('translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('translations_pkey')),
    sa.UniqueConstraint('locale', 'key', name=op.f('uix_locale_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translations_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_translations_key'), ['key'], unique=False)

    # ### end Alembic commands ###
